<?php

namespace prestashop\prestashopWebserviceLib\Shared\Domain;

class Resources
{
    public const ADDRESSES = 'addresses';
    public const ATTACHMENTS = 'attachments';
    public const CARRIERS = 'carriers';
    public const CART_RULES = 'cart_rules';
    public const CARTS = 'carts';
    public const CATEGORIES = 'categories';
    public const COMBINATIONS = 'combinations';
    public const CONFIGURATIONS = 'configurations';
    public const CONTACTS = 'contacts';
    public const CONTENT_MANAGEMENT_SYSTEM = 'content_management_system';
    public const COUNTRIES = 'countries';
    public const CURRENCIES = 'currencies';
    public const CUSTOMER_MESSAGES = 'customer_messages';
    public const CUSTOMER_THREADS = 'customer_threads';
    public const CUSTOMERS = 'customers';
    public const CUSTOMIZATIONS = 'customizations';
    public const DELIVERIES = 'deliveries';
    public const EMPLOYEES = 'employees';
    public const GROUPS = 'groups';
    public const GUESTS = 'guests';
    public const IMAGE_TYPES = 'image_types';
    public const IMAGES = 'images';
    public const LANGUAGES = 'languages';
    public const MANUFACTURERS = 'manufacturers';
    public const MESSAGES = 'messages';
    public const ORDER_CARRIERS = 'order_carriers';
    public const ORDER_CART_RULES = 'order_cart_rules';
    public const ORDER_DETAILS = 'order_details';
    public const ORDER_HISTORIES = 'order_histories';
    public const ORDER_INVOICES = 'order_invoices';
    public const ORDER_PAYMENTS = 'order_payments';
    public const ORDER_SLIPS = 'order_slips';
    public const ORDER_STATES = 'order_states';
    public const ORDERS = 'orders';
    public const PRICE_RANGES = 'price_ranges';
    public const PRODUCT_CUSTOMIZATION_FIELDS = 'product_customization_fields';
    public const PRODUCT_FEATURE_VALUES = 'product_feature_values';
    public const PRODUCT_FEATURES = 'product_features';
    public const PRODUCT_OPTION_VALUES = 'product_option_values';
    public const PRODUCT_OPTIONS = 'product_options';
    public const PRODUCT_SUPPLIERS = 'product_suppliers';
    public const PRODUCTS = 'products';
    public const SEARCH = 'search';
    public const SHOP_GROUPS = 'shop_groups';
    public const SHOP_URLS = 'shop_urls';
    public const SHOPS = 'shops';
    public const SPECIFIC_PRICE_RULES = 'specific_price_rules';
    public const SPECIFIC_PRICES = 'specific_prices';
    public const STATES = 'states';
    public const STOCK_AVAILABLES = 'stock_availables';
    public const STOCK_MOVEMENT_REASONS = 'stock_movement_reasons';
    public const STOCK_MOVEMENTS = 'stock_movements';
    public const STOCKS = 'stocks';
    public const STORES = 'stores';
    public const SUPPLIERS = 'suppliers';
    public const SUPPLY_ORDER_DETAILS = 'supply_order_details';
    public const SUPPLY_ORDER_HISTORIES = 'supply_order_histories';
    public const SUPPLY_ORDER_RECEIPT_HISTORIES = 'supply_order_receipt_histories';
    public const SUPPLY_ORDER_STATES = 'supply_order_states';
    public const SUPPLY_ORDERS = 'supply_orders';
    public const TAGS = 'tags';
    public const TAX_RULE_GROUPS = 'tax_rule_groups';
    public const TAX_RULES = 'tax_rules';
    public const TAXES = 'taxes';
    public const TRANSLATED_CONFIGURATIONS = 'translated_configurations';
    public const WAREHOUSE_PRODUCT_LOCATIONS = 'warehouse_product_locations';
    public const WAREHOUSES = 'warehouses';
    public const WEIGHT_RANGES = 'weight_ranges';
    public const ZONES = 'zones';
}